project = 'wonderful'
title = 'wonderful API reference'
description = 'The *wonderful* GUI library.'
full_description = [[
This is the API reference for the wonderful library.]]

examples = 'examples'

topics = 'doc/manual'
use_markdown_titles = true

file = {
  'buffer/src',
  'core/src',
  'common/src',
  'components/src'
}

dir = 'doc/html/'

kind_names = {
  topic = 'Manual',
}

format = 'discount'
no_space_before_args = true
wrap = true
